apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-provisioner
  labels:
    app: nfs-provisioner
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
    - name: nfs-udp
      port: 2049
      protocol: UDP
    - name: nlockmgr
      port: 32803
      protocol: TCP
    - name: nlockmgr-udp
      port: 32803
      protocol: UDP
    - name: mountd
      port: 20048
      protocol: TCP
    - name: mountd-udp
      port: 20048
      protocol: UDP
    - name: rquotad
      port: 875
      protocol: TCP
    - name: rquotad-udp
      port: 875
      protocol: UDP
    - name: rpcbind
      port: 111
      protocol: TCP
    - name: rpcbind-udp
      port: 111
      protocol: UDP
    - name: statd
      port: 662
      protocol: TCP
    - name: statd-udp
      port: 662
      protocol: UDP
  selector:
    app: nfs-provisioner