kind: ServiceAccount
apiVersion: v1
metadata:
  name: defer-admin-account
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: defer-admin-role
  namespace: default
rules:
  # All the groups/resources/verbs used within the golang client
  # Eventually create more specific roles
  - apiGroups: ["", "apps", "batch", "chaos-mesh.org"]
    resources: ["deployments", "jobs", "services", "endpoints", "configmaps", "nodes", "persistentvolumes", "statefulsets",
                "serviceaccounts", "workflows", "networkchaos"]
    verbs: ["create", "delete", "get", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: defer-admin-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: defer-admin-account
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: defer-admin-role
  apiGroup: rbac.authorization.k8s.io