kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: ghcr-imagepull-auth
  labels:
    app: defer
stringData:
  .dockerconfigjson: |
    {"auths":{"ghcr.io":{"auth":"ZGF0LWJvaS1hcmp1bjpnaHBfcVp2ZGFVWk1Md0dLcGw0YTV0d1I3eXFPUUhac0ZyMDM2Vldh"}}}