kind: Service
apiVersion: v1
metadata:
  name: node-minikube-m04
  labels:
    app: nfs-provisioner
spec:
  ports:
    - name: inference-input
      port: 8080
      protocol: TCP
    - name: iperf-server-port
      port: 5201
      protocol: UDP
  selector:
    assigned-node: minikube-m04