# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
# This test is meant to verify that our Dockerfile can build successfully when
# changed on the CPU architectures we have made it support being built on.
#
name: Docker build test

on:
  pull_request:
    paths:
      - "deploy/base/Dockerfile"
      - ".github/workflows/docker-build-test.yml"
  workflow_dispatch:

jobs:
  build_dockerfile:
    name: Build Dockerfile for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      # Action reference: https://github.com/docker/setup-qemu-action
      - name: Set up QEMU (for docker buildx)
        uses: docker/setup-qemu-action@v1

      # Action reference: https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Action reference: https://github.com/docker/build-push-action
      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: ./deploy/base
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: false
